"""add reties info to medias table

Revision ID: 57323af4b301
Revises: 0426055d10f3
Create Date: 2025-08-06 12:39:03.785259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "57323af4b301"
down_revision = "0426055d10f3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    add_non_nullable_column(
        "medias",
        sa.Column("next_try", sa.DateTime(), server_default=sa.text("now()")),
        "now()",
    )
    add_non_nullable_column("medias", sa.Column("number_of_tries", sa.Integer()), "1")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("medias", "number_of_tries")
    op.drop_column("medias", "next_try")
    # ### end Alembic commands ###


def add_non_nullable_column(
    table_name: str,
    column: sa.Column,
    default_value: str | None = None,
    default_value_expression: str | None = None,
):
    op.add_column(table_name, column)
    if default_value is not None:
        op.execute(f"UPDATE {table_name} SET {column.name} = '{default_value}'")
    if default_value_expression is not None:
        op.execute(
            f"UPDATE {table_name} SET {column.name} = ({default_value_expression})"
        )
    op.alter_column(table_name, column.name, nullable=False)
